export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const ADD_SUCCESS = "ADD_SUCCESS"
export const REFRESH_LIST = "REFRESH_LIST"
export const Remove_SUCCESS = "Remove_SUCCESS"
export const UPDATE_TASK = "UPDATE_TASK"
export const REFRESH_USER = "REFRESH_USER"